name: Git Mirroring
on: workflow_dispatch
#on:
#  schedule:
#    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      run: git clone --bare https://gitlab.freedesktop.org/wlroots/wlroots.git
    - name: push
      run: |
          cd wlroots.git
          git config --local user.email "wlroots@ktlwap.com"
          git config --local user.name "wlroots Automation"
          git push --mirror https://github.com/ktlwap/wlroots.git
